"""LLM seam: fallback translation for Power Fx the rule engine can't map.

The LLM never writes files — it only returns a JS replacement for one formula,
which is syntax-validated before acceptance. All requests/responses are logged
to .runs/ for reproducibility.
"""
from __future__ import annotations

import json
import hashlib
import math
import os
import subprocess
import time
from pathlib import Path
from typing import Any

from .fx.function_map import FUNCTION_MAP

SYSTEM_PROMPT = """You translate Microsoft Power Fx expressions to plain JavaScript
for a Google Apps Script web app client. Rules:
- Return ONLY JSON with keys "js", "notes", "confidence" (0.0-1.0).
  The "js" value is the JavaScript translation; use null ONLY if translation is
  genuinely impossible (not merely because a helper is missing).
- You may use standard browser JavaScript: Math, Date, JSON, String, Number,
  Array, encodeURIComponent, window, document, Promise, async/await.
- You may use these pre-existing globals (already generated by the converter):
  state  — object holding global app variables and data sources
  FXRuntime.variable(screenName, name, () => state[name]) — read a variable,
    preserving screen-local shadowing (including Blank) before global fallback
  FXRuntime.updateContext(screenName, record) — update screen-local variables;
    always use the formula's defining screen, including after await/navigation
  FXRuntime.setState(record) — Set updates globals, even if a local shadows them
    Keep variable names unchanged; normalize data column names to snake_case.
  apiCreate(ds, record), apiPatch(ds, base, record), apiRemove(ds, record),
  apiRemoveIf(ds, predicateFn), refreshData(ds)  — data layer (await them)
  go(screenName, optionalContextRecord), goBack()  — navigation
  toast(msg)  — user notification
  val('ControlName')  — read a control's current value (.text, .value, .checked)
  selectControl('ControlName')  — programmatically "press" another control
  resetControl('ControlName')  — restore a generated input's default
  submitForm('FormName'), resetForm('FormName'), setFormMode('FormName', mode)
    — use the generated Form/DataCard runtime contract (await submitForm)
  item  — the current row inside per-row (lambda) context
- Use the FX.* helper namespace for Power Fx table/text/math functions (below).
- Behavior formulas (event handlers like OnSelect) may be one or more statements.
  Value formulas (Text, Visible, Fill...) must be a single pure expression.
- Preserve the original semantics. Prefer a plain-JS equivalent over refusing:
  e.g. date/time parts via Date methods, timezone offset via
  a Date instance's getTimezoneOffset() (same sign as Power Fx TimeZoneOffset:
  positive west of UTC, negative east; use the supplied date for DST).
- Do not invent form fields or bypass the generated Form/DataCard contract.
- Do not use dynamic code evaluation, imports, direct network requests, or
  prototype access. Do not invent FX or FXRuntime helpers.

Available FX.* helpers:
{fx_api}
"""


def build_system_prompt() -> str:
    """Insert the function-coverage table without str.format brace collisions."""
    return SYSTEM_PROMPT.replace("{fx_api}", _fx_api_reference())


def _fx_api_reference() -> str:
    lines = []
    for name, spec in sorted(FUNCTION_MAP.items()):
        js = spec.js.replace("{a0}", "x").replace("{a1}", "y").replace("{a2}", "z").replace("{args}", "...")
        lines.append(f"- {name}(...)  ->  {js}")
    return "\n".join(lines)


def _js_rejection(js: str, behavior: bool) -> str | None:
    """Validate an LLM-proposed JS replacement before acceptance.

    Behavior formulas may be statements; value formulas must be a single
    expression (wrapped so `node --check` accepts bare expressions).
    """
    from .validate import js_syntax_ok  # local import: avoid cycle with llm.py

    if not isinstance(js, str) or not js.strip():
        return "proposal must be nonempty JavaScript text"
    if len(js) > 50000:
        return "proposal exceeds the single-formula size limit"
    body = js.strip()
    # Check in the same async handler context as synthesis. Top-level `await`
    # is invalid in a script but valid in a generated behavior handler.
    wrapped = f"async function proposal() {{\n{body}\n}}" if behavior else f"(\n{body}\n)"
    ok, error = js_syntax_ok(wrapped)
    if not ok:
        return "JavaScript syntax check failed: " + error
    checker = Path(__file__).resolve().parents[2] / "scripts/check_llm_formula.cjs"
    try:
        run = subprocess.run(["node", str(checker)],
            input=json.dumps({"js": body, "behavior": behavior}), text=True,
            capture_output=True, timeout=10, check=True)
        result = json.loads(run.stdout)
        return None if result.get("ok") else result.get("error", "formula contract check failed")
    except (OSError, subprocess.SubprocessError, json.JSONDecodeError):
        return "formula parser is unavailable; rebuild the project image"


def _js_acceptable(js: str, behavior: bool) -> bool:
    return _js_rejection(js, behavior) is None


def _apply_env_file() -> None:
    """Load PFX2GAS_* keys from a .env file (cwd upward), without overriding
    real environment variables. Stdlib-only; silent if no file exists."""
    import os as _os
    from pathlib import Path as _Path

    cwd = _Path.cwd()
    for candidate in [cwd, *cwd.parents]:
        env_file = candidate / ".env"
        if env_file.exists():
            try:
                for raw in env_file.read_text().splitlines():
                    line = raw.strip()
                    if not line or line.startswith("#") or "=" not in line:
                        continue
                    key, _, value = line.partition("=")
                    key, value = key.strip(), value.strip().strip("'\"")
                    if key.startswith("PFX2GAS_") and key not in _os.environ:
                        _os.environ[key] = value
            except OSError:
                pass
            break  # only the nearest .env applies


class LlmClient:
    """Thin OpenAI-compatible client; provider/key come from env (or .env)."""

    def __init__(self, base_url: str | None = None, api_key: str | None = None,
                 model: str | None = None, log_dir: str | Path = ".runs"):
        _apply_env_file()
        self.base_url = base_url or os.environ.get("PFX2GAS_LLM_BASE_URL")
        self.api_key = api_key or os.environ.get("PFX2GAS_LLM_API_KEY", "")
        self.model = model or os.environ.get("PFX2GAS_LLM_MODEL", "gpt-4o-mini")
        self.log_dir = Path(log_dir)
        self.log_dir.mkdir(parents=True, exist_ok=True)
        self._client: Any | None = None

    @property
    def available(self) -> bool:
        return bool(self.base_url and self.api_key)

    def _get_client(self):
        if self._client is None:
            from openai import OpenAI
            self._client = OpenAI(base_url=self.base_url, api_key=self.api_key)
        return self._client

    def translate_formula(self, fx: str, context: str, behavior: bool = False) -> dict | None:
        """Return {'js': str, 'notes': str, 'confidence': float} or None on failure."""
        if not self.available:
            return None
        client = self._get_client()
        prompt = build_system_prompt()
        kind = "behavior (async event handler)" if behavior else "value (single synchronous expression)"
        user = f"Context: {context}\nFormula kind: {kind}\n\nPower Fx formula:\n{fx}"
        t0 = time.time()
        try:
            resp = client.chat.completions.create(
                model=self.model,
                messages=[{"role": "system", "content": prompt},
                          {"role": "user", "content": user}],
                temperature=0,
                response_format={"type": "json_object"},
            )
            content = resp.choices[0].message.content or ""
        except Exception as exc:  # network, auth, provider errors — degrade to stub
            self._log(fx, {"error": str(exc)}, t0)
            return None
        try:
            data = json.loads(content)
            if not isinstance(data, dict):
                raise ValueError("response must be an object")
            js = data.get("js")
            if js is None:
                self._log(fx, data, t0)
                return None
            confidence = data.get("confidence", 0.5)
            if (not isinstance(js, str) or not isinstance(data.get("notes", ""), str)
                    or isinstance(confidence, bool) or not isinstance(confidence, (int, float))
                    or not math.isfinite(confidence) or not 0 <= confidence <= 1):
                self._log(fx, {"rejected_schema": data}, t0)
                return None
            rejection = _js_rejection(js, behavior)
            if rejection:
                self._log(fx, {"rejected_formula": data, "reason": rejection}, t0)
                return None
            result = {"js": js, "notes": data.get("notes", ""),
                      "confidence": float(confidence)}
            self._log(fx, result, t0)
            return result
        except (json.JSONDecodeError, ValueError, TypeError):
            self._log(fx, {"unparseable": content[:500]}, t0)
            return None

    def _log(self, fx: str, data: dict, t0: float) -> None:
        entry = {"ts": time.time(), "elapsed_s": round(time.time() - t0, 2), "fx": fx,
                 "model": self.model, "formulaSha256": hashlib.sha256(fx.encode()).hexdigest(),
                 "gateVersion": 3, **data}
        with (self.log_dir / "llm-calls.jsonl").open("a") as f:
            f.write(json.dumps(entry, default=str) + "\n")
