"""Stage 6: generate conversion-report.md from the IR + support matrix."""
from __future__ import annotations

from collections import Counter

from .ir import AppIR


def _screen_table(ir: AppIR) -> str:
    lines = ["| Screen | Control | Property | Status | Original formula |",
             "|---|---|---|---|---|"]
    for screen in ir.screens:
        for ctrl in screen.walk_controls():
            for pname, expr in ctrl.properties.items():
                if not expr.raw:
                    continue
                status = "converted" if expr.js and "FX.unsupported" not in expr.js else \
                    ("partial" if expr.js else "stubbed")
                raw = expr.raw.replace("|", "\\|").replace("\n", " ")[:70]
                lines.append(f"| {screen.name} | {ctrl.name} | {pname} | {status} | `{raw}` |")
    return "\n".join(lines) if len(lines) > 2 else "_No formulas found._"


def _risk_section(review_rows: list[dict]) -> str:
    if not review_rows:
        return ("_Behavioral review not run_ (LLM not configured or `--no-review` / "
                "`--no-llm` used). Every converted formula should still be smoke-tested.\n")
    lines = ["| Risk | Where | Why | What to do |", "|---|---|---|---|"]
    order = {"high": 0, "medium": 1, "low": 2}
    for row in sorted(review_rows, key=lambda r: order.get(r["risk"], 3)):
        reason = row["reason"].replace("|", "\\|")[:120]
        suggestion = row["suggestion"].replace("|", "\\|")[:120]
        lines.append(f"| **{row['risk']}** | {row['context']} | {reason} | {suggestion} |")
    return "\n".join(lines) + "\n"


def _qa_section(qa_scenarios: list[dict]) -> str:
    if not qa_scenarios:
        return ("_No QA scenarios generated_ (LLM not configured or review disabled).\n")
    parts = []
    for i, s in enumerate(qa_scenarios, 1):
        steps = "\n".join(f"   {n}. {step}" for n, step in enumerate(s.get("steps", []), 1))
        parts.append(
            f"### {i}. {s.get('title', 'Scenario')}\n"
            f"Covers: {s.get('covers', '—')}\n\n"
            f"1. Steps:\n{steps}\n"
            f"1. **Expected:** {s.get('expected', '—')}\n"
        )
    return "\n".join(parts)


def _data_table(ir: AppIR) -> str:
    if not ir.data_sources:
        return "_No external data sources._"
    lines = ["| Data source | Kind | Origin | Fields | Storage in converted app |",
             "|---|---|---|---|---|"]
    for ds in ir.data_sources:
        if ds.origin == "collection":
            kind, storage = "collection", "client-side state array (not persisted)"
        else:
            kind, storage = "table", f"Google Sheet tab `{ds.name}`"
        fields = ", ".join(f"{f.name} ({f.type})" for f in ds.fields) or "_none inferred_"
        lines.append(f"| {ds.name} | {kind} | {ds.origin} | {fields} | {storage} |")
    return "\n".join(lines)


def _followups(ir: AppIR) -> str:
    items = []
    for entry in ir.support_matrix:
        if entry.status in {"stubbed", "unmapped"}:
            items.append(f"- [ ] `{entry.subject}` — {entry.detail}")
    if not items:
        items.append("_None — every formula was transpiled by rules._")
    return "\n".join(items)


def render_report(ir: AppIR, validation: dict | None = None,
                  review_rows: list[dict] | None = None,
                  qa_scenarios: list[dict] | None = None) -> str:
    counts = Counter(e.status for e in ir.support_matrix)
    total_formulas = sum(
        1 for s in ir.screens for c in s.walk_controls() for e in c.properties.values() if e.raw
    )
    stub_note = ""
    if validation is not None:
        stub_note = f"\n**Validator:** {'PASS' if validation['ok'] else 'FAIL'}"
        if validation.get("problems"):
            stub_note += " — " + "; ".join(validation["problems"])
        stub_note += f" — {validation.get('stub_count', 0)} unsupported-function call sites emitted."

    return f"""# Conversion report — {ir.name}

Generated by pfx2gas. This app was converted from Power Apps to a Google Apps
Script web app. Everything below is a map of what was converted and what needs
human attention.

## Summary

- **Screens:** {len(ir.screens)} ({', '.join(s.name for s in ir.screens) or 'none'})
- **Controls:** {sum(1 for s in ir.screens for c in s.walk_controls())}
- **Formulas found:** {total_formulas}
- **Rule-transpiled:** {total_formulas - counts.get('stubbed', 0) - counts.get('unmapped', 0)}
- **Stubbed / unmapped:** {counts.get('stubbed', 0) + counts.get('unmapped', 0)}
- **Global variables:** {', '.join(f'`{v}`' for v in ir.global_vars) or 'none'}
{stub_note}

## Data mapping

Original data sources are mapped to tabs of one Google Sheet workbook
(created by running `setup()` from `DataInit.gs` once after deploy).

{_data_table(ir)}

## Screens & formulas

{_screen_table(ir)}

## Behavioral-equivalence review

{_risk_section(review_rows or [])}

## Manual QA scenarios

{_qa_section(qa_scenarios or [])}

## Manual follow-ups

{_followups(ir)}

## Capacity notes

Apps Script quotas differ from Power Apps: max 6 min per execution (30 min on
Workspace), 30 concurrent executions per script, 30 s response budget for web
app entry points, and URL Fetch 20k calls/day (consumer). The generated data
layer reads whole tabs into memory; keep tabs under ~5,000 rows or add
filtering server-side.

## Known limitations

- Power Automate flows, Dataverse-specific features, delegated queries, and
  custom components are out of scope; anything in this app that used them was
  flagged above rather than silently dropped.
- Power Fx delegation semantics are not reproduced: all filtering happens
  client-side over the full tab.
"""
