"""Stage 4b: synthesize the client side (Index.html, App.js) from the IR.

UI-parity notes:
- Static numeric X/Y/Width/Height/ZIndex become inline absolute-position styles.
- Reactive visual properties (Fill, Color, Size, FontSize, Visible, Align...)
  are registered as styleControl evaluators so they re-apply on state change.
- Galleries render their row template per item via FXRuntime.gallery, with
  per-row child handlers bound to the item (ThisItem semantics).
"""
from __future__ import annotations

from ..ir import AppIR, ControlNode
from .server import data_sources_with_fields  # noqa: F401  (kept for API compat)

ELEMENT_MAP = {
    "Button": "button",
    "Label": "span",
    "TextInput": "input",
    "TextArea": "textarea",
    "Dropdown": "select",
    "ComboBox": "select",
    "CheckBox": "input",
    "DatePicker": "input",
    "Gallery": "div",
    "Image": "img",
    "Icon": "span",
    "HtmlText": "div",
    "Form": "div",
    "Screen": "section",
}

POSITION_PROPS = ("X", "Y", "Width", "Height", "ZIndex")
# Reactive visual properties -> CSS property + unit mode
STYLE_EVAL_PROPS = {
    "X": ("left", "px"),
    "Y": ("top", "px"),
    "Width": ("width", "px"),
    "Height": ("height", "px"),
    "Fill": ("backgroundColor", "lower"),
    "Color": ("color", "lower"),
    "Size": ("fontSize", "px"),
    "FontSize": ("fontSize", "px"),
    "FontWeight": ("fontWeight", None),
    "Align": ("textAlign", "lower"),
}

STATIC_TEXT_CONTROLS = {"Button", "Label"}


def _static_position_style(ctrl: ControlNode) -> str:
    """Inline style string from static numeric position/size properties."""
    parts = []
    for prop in POSITION_PROPS:
        expr = ctrl.properties.get(prop)
        if not expr or expr.js is None:
            continue
        js = expr.js.strip()
        if js.replace(".", "").isdigit():  # plain numeric literal
            css = {"X": "left", "Y": "top", "Width": "width",
                   "Height": "height", "ZIndex": "z-index"}[prop]
            parts.append(f"{css}:{js}px" if prop != "ZIndex" else f"{css}:{js}")
    return ";".join(parts)


def _static_text(ctrl: ControlNode) -> str:
    expr = ctrl.properties.get("Text")
    if expr and ctrl.type in STATIC_TEXT_CONTROLS and expr.js and expr.js.startswith("'"):
        return expr.js[1:-1]  # unwrap the string literal
    return ""


def _render_control(ctrl: ControlNode, depth: int) -> str:
    tag = ELEMENT_MAP.get(ctrl.type, "div")
    indent = "  " * (depth + 1)
    style = _static_position_style(ctrl)
    style_attr = f' style="{style}"' if style else ""
    extra = ""
    if ctrl.type in {"TextInput", "TextArea"}:
        extra = ' type="text"'
    elif ctrl.type == "CheckBox":
        extra = ' type="checkbox"'
    elif ctrl.type == "DatePicker":
        extra = ' type="date"'

    if ctrl.type == "Gallery":
        inner_row = "\n".join(_render_control(c, depth + 2) for c in ctrl.children)
        return (
            f'{indent}<div data-control="{ctrl.name}"{style_attr} class="fx-gallery">\n'
            f'{indent}  <div class="fx-rows"></div>\n'
            f'{indent}  <template>\n'
            f'{indent}    <div class="fx-row">\n{inner_row}\n{indent}    </div>\n'
            f'{indent}  </template>\n'
            f'{indent}</div>'
        )

    inner = ""
    close = f"</{tag}>" if tag not in {"input", "img", "br", "hr"} else ""
    if ctrl.children:
        inner = "\n" + "\n".join(_render_control(c, depth + 1) for c in ctrl.children) + "\n" + indent
    return f'{indent}<{tag} data-control="{ctrl.name}"{style_attr}{extra}>{_static_text(ctrl)}{inner}{close}'


def render_screens_html(ir: AppIR) -> str:
    parts = []
    for screen in ir.screens:
        parts.append(f'  <section data-screen="{screen.name}" style="display:none">')
        for ctrl in screen.controls:
            parts.append(_render_control(ctrl, 1))
        parts.append("  </section>")
    return "\n".join(parts)


def render_app_js(ir: AppIR) -> str:
    lines = [
        "// App.js — generated by pfx2gas; transpiled Power Fx lives here.",
        "APP_MAIN = async function () {",
    ]
    for ds in ir.data_sources:
        if ds.fields:
            lines.append(f"  refreshData({ds.name!r});")
    if ir.on_start and ir.on_start.js:
        lines.append("  // OnStart (transpiled from Power Fx)")
        for stmt in ir.on_start.js.splitlines():
            lines.append(f"  {stmt}")
    lines.append("  var __INITIAL_STATE_ONLY = null;")
    lines.append("")

    for screen in ir.screens:
        if screen.on_visible and screen.on_visible.js:
            lines.append(f"  FXRuntime.registerScreenHandler({screen.name!r}, async function () {{")
            for stmt in screen.on_visible.js.splitlines():
                lines.append(f"    {stmt}")
            lines.append("  });")

    for screen in ir.screens:
        for ctrl in screen.walk_controls():
            # --- event bindings -------------------------------------------
            for event in ("OnSelect", "OnChange"):
                expr = ctrl.properties.get(event)
                if expr and expr.js:
                    lines.append(f"  // {ctrl.name}.{event}")
                    lines.append(f"  bind({ctrl.name!r}, {event!r}, async function () {{")
                    for stmt in expr.js.splitlines():
                        lines.append(f"    {stmt}")
                    lines.append("  });")

            # --- gallery rendering ----------------------------------------
            if ctrl.type == "Gallery":
                items = ctrl.properties.get("Items")
                if items and items.js:
                    row_fns = []
                    handlers = {}
                    for child in ctrl.children:
                        texpr = child.properties.get("Text")
                        if texpr and texpr.js and not texpr.js.startswith("'"):
                            row_fns.append(
                                f"        var el_{child.name} = row.querySelector('[data-control=\"{child.name}\"]');"
                                f" if (el_{child.name}) el_{child.name}.textContent = {texpr.js};"
                            )
                        onsel = child.properties.get("OnSelect")
                        if onsel and onsel.js:
                            handlers[child.name] = onsel.js
                    lines.append(f"  // {ctrl.name}.Items (gallery)")
                    lines.append("  FXRuntime.gallery(")
                    lines.append(f"    {ctrl.name!r},")
                    lines.append(f"    function () {{ return {items.js}; }},")
                    lines.append("    function (item, row) {")
                    for rf in row_fns:
                        lines.append(rf)
                    lines.append("    },")
                    if handlers:
                        lines.append("    {")
                        for cname, js in handlers.items():
                            lines.append(f"      {cname}: async function (item) {{")
                            for stmt in js.splitlines():
                                lines.append(f"        {stmt}")
                            lines.append("      },")
                        lines.append("    }")
                    else:
                        lines.append("    null")
                    lines.append("  );")

            # --- reactive text --------------------------------------------
            text_expr = ctrl.properties.get("Text")
            if (text_expr and text_expr.js and not text_expr.js.startswith("'")
                    and ctrl.type not in {"Gallery"}):
                lines.append(f"  // {ctrl.name}.Text (reactive)")
                lines.append("  FXRuntime.addEvaluator(function () {")
                lines.append('    var el = document.querySelector(\'[data-control="' + ctrl.name + '"]\');')
                lines.append("    if (el) el.textContent = " + text_expr.js + ";")
                lines.append("  });")

            # --- reactive visual properties -------------------------------
            for prop, (css, unit) in STYLE_EVAL_PROPS.items():
                expr = ctrl.properties.get(prop)
                if not expr or not expr.js or expr.js.strip().isdigit():
                    continue  # static numeric values already inline in HTML
                lines.append(f"  // {ctrl.name}.{prop} (reactive style)")
                lines.append(f"  FXRuntime.styleControl({ctrl.name!r}, {css!r}, function () {{")
                lines.append(f"    return {expr.js};")
                lines.append(f"  }}, {unit!r});")

            # --- visibility -------------------------------------------------
            vis = ctrl.properties.get("Visible")
            if vis and vis.js:
                lines.append(f"  // {ctrl.name}.Visible (reactive)")
                lines.append(f"  FXRuntime.styleControl({ctrl.name!r}, 'display', function () {{")
                lines.append(f"    return ({vis.js}) ? '' : 'none';")
                lines.append("  }, null);")
    lines.append("};")
    return "\n".join(lines)


INDEX_CSS = """
    body { font-family: system-ui, sans-serif; margin: 0; padding: 16px; }
    [data-screen] { max-width: 100%%; margin: 0 auto; position: relative; min-height: 90vh; }
    [data-screen] > [data-control] { position: absolute; }
    button { cursor: pointer; }
    input, select, textarea { box-sizing: border-box; }
    .fx-gallery { overflow: auto; }
    .fx-rows { display: block; }
    .fx-row { display: block; position: relative; border-bottom: 1px solid #eee; padding: 4px 0; }
    .fx-toast { position: fixed; bottom: 16px; left: 50%%; transform: translateX(-50%%);
      background: #333; color: #fff; padding: 8px 16px; border-radius: 4px; display: none; z-index: 9999; }
    .fx-toast.error { background: #b3261e; }
"""


def render_index_html(ir: AppIR, screens_html: str) -> str:
    return f"""<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{ir.name}</title>
  <style>{INDEX_CSS}</style>
  <base target="_top">
</head>
<body>
<?!= include('Screens'); ?>
<script>
<?!= include('gas-runtime'); ?>
<?!= include('fx-stdlib'); ?>
<?!= include('App'); ?>
</script>
</body>
</html>
"""
