"""Stage 4b: synthesize the client side (Index.html, App.js) from the IR."""
from __future__ import annotations

from ..ir import AppIR, ControlNode, ScreenNode
from ..fx.emitter import _snake

VALUE_PROPS = {"Text", "Default", "Visible"}
# HTML element per control type
ELEMENT_MAP = {
    "Button": "button",
    "Label": "span",
    "TextInput": "input",
    "TextArea": "textarea",
    "Dropdown": "select",
    "ComboBox": "select",
    "CheckBox": "input",
    "DatePicker": "input",
    "Gallery": "div",
    "Image": "img",
    "Icon": "span",
    "HtmlText": "div",
    "Form": "div",
    "Screen": "section",
}


def _escaped_static(text: str) -> str:
    return text


def _render_control(ctrl: ControlNode, depth: int) -> str:
    tag = ELEMENT_MAP.get(ctrl.type, "div")
    indent = "  " * (depth + 1)
    attrs = [f'data-control="{ctrl.name}"']
    extra = ""
    if ctrl.type in {"TextInput", "TextArea"}:
        extra = ' type="text"'
    elif ctrl.type == "CheckBox":
        extra = ' type="checkbox"'
    elif ctrl.type == "DatePicker":
        extra = ' type="date"'
    elif ctrl.type == "Button":
        extra = ""
    inner = ""
    close = f"</{tag}>" if tag not in {"input", "img", "br", "hr"} else ""
    if ctrl.children:
        inner = "\n" + "\n".join(_render_control(c, depth + 1) for c in ctrl.children) + "\n" + indent
    text_prop = ctrl.properties.get("Text")
    text = ""
    if text_prop and ctrl.type in {"Button", "Label"} and text_prop.js and text_prop.js.startswith("'"):
        text = text_prop.js[1:-1]  # static string literal
    return f'{indent}<{tag} {"".join(attrs)}{extra}>{text}{inner}{close}'


def render_screens_html(ir: AppIR) -> str:
    """Screen sections embedded into Index.html (include-style partial)."""
    parts = []
    for screen in ir.screens:
        parts.append(f'  <section data-screen="{screen.name}" style="display:none">')
        for ctrl in screen.controls:
            parts.append(_render_control(ctrl, 1))
        parts.append("  </section>")
    return "\n".join(parts)


def render_app_js(ir: AppIR) -> str:
    lines = [
        "// App.js — generated by pfx2gas; transpiled Power Fx lives here.",
        "APP_MAIN = async function () {",
    ]
    # initial data loads
    for ds in ir.data_sources:
        if ds.fields:
            lines.append(f"  refreshData({ds.name!r});")
    # global state initialization from OnStart
    if ir.on_start and ir.on_start.js:
        lines.append("  // OnStart (transpiled from Power Fx)")
        for stmt in ir.on_start.js.splitlines():
            lines.append(f"  {stmt}")
    lines.append("  var __INITIAL_STATE_ONLY = null;")
    lines.append("")
    # screen handlers (OnVisible)
    for screen in ir.screens:
        if screen.on_visible and screen.on_visible.js:
            lines.append(f"  FXRuntime.registerScreenHandler({screen.name!r}, async function () {{")
            for stmt in screen.on_visible.js.splitlines():
                lines.append(f"    {stmt}")
            lines.append("  });")
    # control bindings + property evaluators
    for screen in ir.screens:
        for ctrl in screen.walk_controls():
            for event in ("OnSelect", "OnChange"):
                expr = ctrl.properties.get(event)
                if expr and expr.js:
                    lines.append(f"  // {ctrl.name}.{event}")
                    lines.append(f"  bind({ctrl.name!r}, {event!r}, async function () {{")
                    for stmt in expr.js.splitlines():
                        lines.append(f"    {stmt}")
                    lines.append("  });")
            text_expr = ctrl.properties.get("Text")
            if text_expr and text_expr.js and not text_expr.js.startswith("'"):
                lines.append(f"  // {ctrl.name}.Text (reactive)")
                lines.append("  FXRuntime.addEvaluator(function () {")
                lines.append(f'    var el = document.querySelector(\'[data-control="{ctrl.name}"]\');')
                lines.append("    if (el) el.textContent = " + text_expr.js + ";")
                lines.append("  });")
            visible_expr = ctrl.properties.get("Visible")
            if visible_expr and visible_expr.js:
                lines.append(f"  // {ctrl.name}.Visible (reactive)")
                lines.append("  FXRuntime.addEvaluator(function () {")
                lines.append(f'    var el = document.querySelector(\'[data-control="{ctrl.name}"]\');')
                lines.append("    if (el) el.style.display = (" + visible_expr.js + ") ? '' : 'none';")
                lines.append("  });")
    lines.append("};")
    return "\n".join(lines)


INDEX_CSS = """
    body { font-family: system-ui, sans-serif; margin: 0; padding: 16px; }
    [data-screen] { max-width: 720px; margin: 0 auto; }
    button { padding: 8px 16px; margin: 4px 0; cursor: pointer; }
    input, select, textarea { padding: 6px; margin: 4px 0; width: 100%%; box-sizing: border-box; }
    .fx-toast { position: fixed; bottom: 16px; left: 50%%; transform: translateX(-50%%);
      background: #333; color: #fff; padding: 8px 16px; border-radius: 4px; display: none; z-index: 10; }
    .fx-toast.error { background: #b3261e; }
"""


def render_index_html(ir: AppIR, screens_html: str) -> str:
    return f"""<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{ir.name}</title>
  <style>{INDEX_CSS}</style>
  <base target="_top">
</head>
<body>
<?!= include('Screens'); ?>
<script>
<?!= include('gas-runtime'); ?>
<?!= include('fx-stdlib'); ?>
<?!= include('App'); ?>
</script>
</body>
</html>
"""
