"""Stage 4a: synthesize the server side (Code.gs, Data.gs, DataInit.gs, manifest)."""
from __future__ import annotations

from ..ir import AppIR

CODE_GS = """/**
 * Code.gs — web app entry point + API dispatcher.
 * Generated by pfx2gas from {app_name!r}; edit freely after generation.
 */
var ALLOWED_DATA_SOURCES = {data_sources_json};

function assertDataSource(ds) {{
  if (ALLOWED_DATA_SOURCES.indexOf(ds) < 0) {{
    throw new Error('data source is not part of this generated app: ' + ds);
  }}
}}

function assertRecord(value, label) {{
  if (!value || typeof value !== 'object' || Array.isArray(value)) {{
    throw new Error(label + ' must be an object');
  }}
}}

function doGet() {{
  return HtmlService.createTemplateFromFile('Index')
    .evaluate()
    .setTitle({app_name!r})
    .addMetaTag('viewport', 'width=device-width, initial-scale=1');
}}

/** Single API surface used by the generated client (gas-runtime.js serverRun). */
function api(ds, op, payload) {{
  payload = payload || {{}};
  assertDataSource(ds);
  switch (op) {{
    case 'list': return listRows(ds);
    case 'patch': assertRecord(payload.record, 'patch record'); return patchRow(ds, payload.base, payload.record);
    case 'create': assertRecord(payload.record, 'create record'); return createRow(ds, payload.record);
    case 'remove': assertRecord(payload.record, 'remove record'); return removeRow(ds, payload.record);
    case 'removeIf': return removeRowsByIds(ds, payload.ids);
    default: throw new Error('unknown api op: ' + op);
  }}
}}

function ss() {{
  var props = PropertiesService.getScriptProperties();
  var id = props.getProperty('DATA_SPREADSHEET_ID');
  if (!id) throw new Error('Run DataInit.gs setup() once to create the data workbook.');
  return SpreadsheetApp.openById(id);
}}

/** HtmlService templating helper used by Index.html: inlines another project
 *  file. The .js.html runtime files are stored WITH a <script> wrapper; strip
 *  it so they can be nested inside Index's own <script> block safely. */
function include(name) {{
  var html = HtmlService.createHtmlOutputFromFile(name).getContent();
  return html
    .replace(/^\\s*<script>\\n?/, '')
    .replace(/\\n?<\\/script>\\s*$/, '');
}}

function sheetFor(ds) {{
  var sh = ss().getSheetByName(ds);
  if (!sh) throw new Error('no sheet named ' + ds + '; run setup() again.');
  return sh;
}}

/** Identity for User() (Session user; blank on anonymous deployments). */
function whoami() {{
  try {{
    var user = Session.getActiveUser();
    var email = user.getEmail() || '';
    var local = email.split('@')[0] || '';
    var fullName = local
      .replace(/[._-]+/g, ' ')
      .replace(/\\b\\w/g, function (c) {{ return c.toUpperCase(); }});
    return {{
      email: email,
      fullName: fullName,
      pictureUrl: ''
    }};
  }} catch (err) {{
    return {{ email: '', fullName: '', pictureUrl: '' }};
  }}
}}

/** Choice metadata for Choices(): rows are [{{Name, Value}}] per field. */
function apiChoices(ds, field) {{
  assertDataSource(ds);
  var sh = ss().getSheetByName('__Choices');
  if (!sh) return [];
  var values = sh.getDataRange().getValues();
  var headers = values[0] || [];
  var col = headers.indexOf(ds + '.' + field);
  if (col < 0) return [];
  return values.slice(1)
    .map(function (row) {{ return row[col]; }})
    .filter(function (v) {{ return v !== ''; }})
    .map(function (v) {{ return {{ Name: v, Value: v }}; }});
}}

function listRows(ds) {{
  var sh = sheetFor(ds);
  var values = sh.getDataRange().getValues();
  if (values.length < 2) return [];
  var headers = values[0];
  return values.slice(1).map(function (row) {{
    var obj = {{}};
    headers.forEach(function (h, i) {{
      obj[h] = row[i] instanceof Date ? row[i].toISOString() : row[i];
    }});
    return obj;
  }});
}}

function createRow(ds, record) {{
  var sh = sheetFor(ds);
  var headers = sh.getRange(1, 1, 1, sh.getLastColumn()).getValues()[0];
  sh.appendRow(headers.map(function (h) {{ return record[h] !== undefined ? record[h] : ''; }}));
  return {{ ok: true }};
}}

function patchRow(ds, base, record) {{
  var sh = sheetFor(ds);
  var values = sh.getDataRange().getValues();
  var headers = values[0] || [];
  var idIdx = headers.indexOf('id');
  var targetRow = -1;
  if (base && idIdx >= 0 && base.id !== undefined && base.id !== null) {{
    for (var r = 1; r < values.length; r++) {{
      if (String(values[r][idIdx]) === String(base.id)) {{ targetRow = r + 1; break; }}
    }}
  }}
  if (targetRow < 0) return createRow(ds, record);
  headers.forEach(function (h, c) {{
    if (record[h] !== undefined) sh.getRange(targetRow, c + 1).setValue(record[h]);
  }});
  return {{ ok: true }};
}}

function removeRow(ds, record) {{
  var sh = sheetFor(ds);
  var values = sh.getDataRange().getValues();
  var headers = values[0] || [];
  var idIdx = headers.indexOf('id');
  if (idIdx < 0) throw new Error('remove requires an id column');
  for (var r = 1; r < values.length; r++) {{
    if (String(values[r][idIdx]) === String(record.id)) {{
      sh.deleteRow(r + 1);
      return {{ ok: true }};
    }}
  }}
  return {{ ok: false }};
}}

function removeRowsByIds(ds, ids) {{
  if (!Array.isArray(ids) || !ids.length) {{
    throw new Error('removeIf requires one or more explicit ids');
  }}
  var sh = sheetFor(ds);
  var values = sh.getDataRange().getValues();
  var headers = values[0] || [];
  var idIdx = headers.indexOf('id');
  if (idIdx < 0) throw new Error('removeIf requires an id column');
  var wanted = ids.map(String);
  for (var r = values.length - 1; r >= 1; r--) {{
    if (wanted.indexOf(String(values[r][idIdx])) >= 0) sh.deleteRow(r + 1);
  }}
  return {{ ok: true }};
}}
"""

DATA_INIT_GS = """/**
 * DataInit.gs — one-time setup: creates the data workbook and tabs.
 * Run setup() once from the Apps Script editor after deploying.
 */
function setup() {{
  var props = PropertiesService.getScriptProperties();
  if (props.getProperty('DATA_SPREADSHEET_ID')) return 'already initialized';
  var workbook = SpreadsheetApp.create({app_name!r} + ' — data');
  var specs = {tabs_json};
  specs.forEach(function (spec) {{
    var sh = workbook.getSheetByName(spec.name) || workbook.insertSheet(spec.name);
    sh.clear();
    var headers = spec.fields.map(function (f) {{ return f[0]; }});
    sh.getRange(1, 1, 1, headers.length).setValues([headers]);
    if (spec.rows && spec.rows.length) {{
      var body = spec.rows.map(function (row) {{
        return headers.map(function (h, i) {{ return row[i] === undefined ? '' : row[i]; }});
      }});
      sh.getRange(2, 1, body.length, headers.length).setValues(body);
    }}
    sh.setFrozenRows(1);
  }});
  var choiceFields = {choices_json};
  var choiceNote = '';
  if (choiceFields.length) {{
    var ch = workbook.insertSheet('__Choices');
    ch.getRange(1, 1, 1, choiceFields.length).setValues([choiceFields]);
    ch.setFrozenRows(1);
    choiceNote = ' Populate the __Choices tab, then reload the app.';
  }}
  var defaultSheet = workbook.getSheetByName('Sheet1');
  if (defaultSheet && workbook.getSheets().length > 1) workbook.deleteSheet(defaultSheet);
  props.setProperty('DATA_SPREADSHEET_ID', workbook.getId());
  return 'created ' + workbook.getUrl() + choiceNote;
}}
"""

MANIFEST = """{{
  "timeZone": "America/New_York",
  "dependencies": {{}},
  "exceptionLogging": "STACKDRIVER",
  "runtimeVersion": "V8",
  "webapp": {{
    "executeAs": "{execute_as}",
    "access": "{access}"
  }},
  "oauthScopes": [
    "https://www.googleapis.com/auth/spreadsheets"
  ]
}}
"""


def data_sources_with_fields(ir: AppIR) -> list:
    """External (non-collection) sources that should get a generated Sheet tab."""
    return [ds for ds in ir.data_sources if ds.origin != "collection" and ds.fields]


def render_code_gs(ir: AppIR) -> str:
    import json

    allowed = [ds.name for ds in data_sources_with_fields(ir)]
    return CODE_GS.format(app_name=ir.name, data_sources_json=json.dumps(allowed))


def render_data_init(ir: AppIR) -> str:
    import json

    from ..fx.naming import snake as _snake

    tabs = []
    for ds in data_sources_with_fields(ir):
        headers = [_snake(f.name) for f in ds.fields]
        rows = []
        for row in ds.sample_data[:100]:
            rows.append([row.get(h, "") for h in headers])
        tabs.append({"name": ds.name, "fields": [[h, f.type]
                                                 for f, h in zip(ds.fields, headers)],
                     "rows": rows})
    return DATA_INIT_GS.format(app_name=ir.name, tabs_json=json.dumps(tabs),
                               choices_json=json.dumps(ir.choice_fields))


def render_manifest(ir: AppIR) -> str:
    # MANIFEST is a format-template ({{ }} are literal braces); without
    # .format() it ships invalid JSON with doubled braces.
    return MANIFEST.format(access=ir.webapp_access, execute_as=ir.webapp_execute_as)
