"""Stage 4a: synthesize the server side (Code.gs, Data.gs, DataInit.gs, manifest)."""
from __future__ import annotations

from ..ir import AppIR

CODE_GS = """/**
 * Code.gs — web app entry point + API dispatcher.
 * Generated by pfx2gas from {app_name!r}; edit freely after generation.
 */
var ALLOWED_DATA_SOURCES = {data_sources_json};
var DATA_CONTRACTS = {contracts_json};
var RELATIONSHIP_CONTRACTS = {relationships_json};
var GOOGLE_SERVICE_ADAPTERS = {services_json};

function assertDataSource(ds) {{
  if (ALLOWED_DATA_SOURCES.indexOf(ds) < 0) {{
    throw new Error('data source is not part of this generated app: ' + ds);
  }}
}}

function assertRecord(value, label) {{
  if (!value || typeof value !== 'object' || Array.isArray(value)) {{
    throw new Error(label + ' must be an object');
  }}
}}

function launchParametersJSON_(event) {{
  // Request values are untrusted text. Escape HTML script terminators even
  // though the payload is application/json, not executable JavaScript.
  return JSON.stringify(event && event.parameter || {{}}).replace(/</g, '\\\\u003c');
}}

function doGet(event) {{
  var template = HtmlService.createTemplateFromFile('Index');
  template.launchParametersJSON = launchParametersJSON_(event);
  // Cache keys belong to this deployed script, independent of launch params.
  // Identified users have separate caches; unidentified sessions share this
  // app's cache within a browser profile, as documented for web storage.
  var email = '';
  try {{ email = Session.getActiveUser().getEmail() || ''; }} catch (err) {{}}
  template.storageContextJSON = JSON.stringify({{
    appId: ScriptApp.getScriptId(), user: email
  }}).replace(/</g, '\\\\u003c');
  return template.evaluate()
    .setTitle({app_name!r})
    .addMetaTag('viewport', 'width=device-width, initial-scale=1');
}}

/** Single API surface used by the generated client (gas-runtime.js serverRun). */
function api(ds, op, payload) {{
  payload = payload || {{}};
  assertDataSource(ds);
  if (op === 'list') return listRows(ds);
  if (op === 'links') return listRelationshipLinks_(ds);
  if (op === 'relationshipSnapshot') return relationshipSnapshot_(ds);
  return withDataWriteLock_(function () {{
    switch (op) {{
      case 'patch': assertRecord(payload.record, 'patch record'); return patchRow(ds, payload.base, payload.record);
      case 'patchRecord': assertRecord(payload.record, 'patch record'); return patchSingleRecord(ds, payload.record);
      case 'create': assertRecord(payload.record, 'create record'); return createRow(ds, payload.record);
      case 'remove': assertRecord(payload.record, 'remove record'); return removeRow(ds, payload.record);
      case 'removeIf': return removeRowsByIds(ds, payload.ids);
      case 'relate': return mutateRelationship_(ds, payload.relationship, payload.base, payload.record, false);
      case 'unrelate': return mutateRelationship_(ds, payload.relationship, payload.base, payload.record, true);
      default: throw new Error('unknown api op: ' + op);
    }}
  }});
}}

function withDataWriteLock_(action) {{
  // Read/modify/write and key lookup/append must share one critical section
  // across all requests to this script, including different Google users.
  var lock = LockService.getScriptLock();
  lock.waitLock(30000);
  try {{ return action(); }}
  finally {{
    try {{ SpreadsheetApp.flush(); }}
    finally {{ lock.releaseLock(); }}
  }}
}}

function ss() {{
  var props = PropertiesService.getScriptProperties();
  var id = props.getProperty('DATA_SPREADSHEET_ID');
  if (!id) throw new Error('Run DataInit.gs setup() once to create the data workbook.');
  return SpreadsheetApp.openById(id);
}}

/** HtmlService templating helper used by Index.html: inlines another project
 *  file. The .js.html runtime files are stored WITH a <script> wrapper; strip
 *  it so they can be nested inside Index's own <script> block safely. */
function include(name) {{
  var html = HtmlService.createHtmlOutputFromFile(name).getContent();
  return html
    .replace(/^\\s*<script>\\n?/, '')
    .replace(/\\n?<\\/script>\\s*$/, '');
}}

function sheetFor(ds) {{
  var sh = ss().getSheetByName(ds);
  if (!sh) throw new Error('no sheet named ' + ds + '; run setup() again.');
  return sh;
}}

/** Identity for User() (Session user; blank on anonymous deployments). */
function whoami() {{
  try {{
    var user = Session.getActiveUser();
    var email = user.getEmail() || '';
    var local = email.split('@')[0] || '';
    var fullName = local
      .replace(/[._-]+/g, ' ')
      .replace(/\\b\\w/g, function (c) {{ return c.toUpperCase(); }});
    return {{
      email: email,
      fullName: fullName,
      pictureUrl: ''
    }};
  }} catch (err) {{
    return {{ email: '', fullName: '', pictureUrl: '' }};
  }}
}}

/** Choice metadata for Choices(): rows are [{{Name, Value}}] per field. */
function apiChoices(ds, field) {{
  assertDataSource(ds);
  var column = contractColumn(ds, field);
  if (column && DATA_CONTRACTS[ds].fields[column].choices.length) {{
    return DATA_CONTRACTS[ds].fields[column].choices;
  }}
  var sh = ss().getSheetByName('__Choices');
  if (!sh) return [];
  var values = sh.getDataRange().getValues();
  var headers = values[0] || [];
  var col = headers.indexOf(ds + '.' + field);
  if (col < 0) return [];
  return values.slice(1)
    .map(function (row) {{ return row[col]; }})
    .filter(function (v) {{ return v !== ''; }})
    .map(function (v) {{ return {{ name: v, value: v }}; }});
}}

function contractColumn(ds, name) {{
  var fields = DATA_CONTRACTS[ds].fields;
  if (Object.prototype.hasOwnProperty.call(fields, name)) return name;
  return Object.keys(fields).find(function (key) {{ return fields[key].aliases.indexOf(name) >= 0; }});
}}

function normalizeRecord(ds, record) {{
  var normalized = {{}};
  Object.keys(record).forEach(function (name) {{
    var key = contractColumn(ds, name);
    if (!key) throw new Error('unknown field in ' + ds + ': ' + name);
    if (Object.prototype.hasOwnProperty.call(normalized, key) && JSON.stringify(normalized[key]) !== JSON.stringify(record[name]))
      throw new Error('conflicting field aliases in ' + ds + ': ' + key);
    normalized[key] = record[name];
  }});
  return normalized;
}}

function recordIdentity(ds, record) {{
  var primary = DATA_CONTRACTS[ds].primaryKey;
  if (!record) return null;
  var names = [primary].concat(DATA_CONTRACTS[ds].fields[primary].aliases);
  var present = names.filter(function (key) {{ return record[key] !== undefined && record[key] !== null && record[key] !== ''; }});
  if (present.some(function (key) {{ return String(record[key]) !== String(record[present[0]]); }}))
    throw new Error('conflicting primary key aliases in ' + ds);
  return present.length ? record[present[0]] : null;
}}

function lookupTarget(spec, value) {{
  var sources = spec.lookupSources || [];
  if (!sources.length) return null; // Missing target metadata cannot be invented.
  if (sources.length === 1 && spec.lookupTargetCount === 1) return sources[0];
  if (!value || typeof value !== 'object' || Array.isArray(value))
    throw new Error('polymorphic lookup requires an unambiguous target record');
  var matches = sources.filter(function (ds) {{
    var contract = DATA_CONTRACTS[ds], primary = contract.primaryKey;
    return [primary].concat(contract.fields[primary].aliases).some(function (key) {{
      return key !== 'id' && value[key] !== undefined && value[key] !== null && value[key] !== '';
    }});
  }});
  if (matches.length !== 1) throw new Error('polymorphic lookup requires an unambiguous target record');
  return matches[0];
}}

function lookupValue(spec, value, exposeAliases, depth) {{
  if (value === undefined || value === null || value === '') return value;
  if ((typeof value !== 'object' || Array.isArray(value)) && typeof value !== 'string')
    throw new Error('lookup requires a record or key');
  if ((depth || 0) > 20) throw new Error('lookup snapshot nesting exceeds 20 levels');
  var target = lookupTarget(spec, value);
  if (!target) return value;
  var contract = DATA_CONTRACTS[target];
  if (typeof value === 'string') {{
    var reference = {{}}; reference[contract.primaryKey] = value; value = reference;
  }}
  if (recordIdentity(target, value) === null) throw new Error('lookup snapshot requires a primary key for ' + target);
  var normalized = {{}};
  Object.keys(value).forEach(function (name) {{
    var field = contractColumn(target, name), key = field || name, item = value[name];
    if (field) {{
      var nested = contract.fields[field];
      if (nested.type === 'lookup') item = lookupValue(nested, item, exposeAliases, (depth || 0) + 1);
      else {{
        var encoded = encodeCell(target, field, item);
        if (nested.type === 'date' && encoded !== '') item = encoded;
      }}
    }}
    if (Object.prototype.hasOwnProperty.call(normalized, key) && JSON.stringify(normalized[key]) !== JSON.stringify(item))
      throw new Error('conflicting lookup field aliases in ' + target + ': ' + key);
    Object.defineProperty(normalized, key, {{value:item, enumerable:true, configurable:true}});
  }});
  if (exposeAliases) Object.keys(normalized).forEach(function (key) {{
    if (!Object.prototype.hasOwnProperty.call(contract.fields, key)) return;
    contract.fields[key].aliases.forEach(function (alias) {{
      Object.defineProperty(normalized, alias, {{value:normalized[key], enumerable:true, configurable:true}});
    }});
  }});
  return normalized;
}}

function encodeCell(ds, field, value) {{
  if (value === undefined || value === null || value === '') return '';
  var spec = DATA_CONTRACTS[ds].fields[field];
  if (!spec) throw new Error('unknown stored field in ' + ds + ': ' + field);
  if (spec.type === 'lookup' || spec.type === 'choices') {{
    if (spec.type === 'lookup' && (typeof value !== 'object' || Array.isArray(value)) && typeof value !== 'string')
      throw new Error('lookup requires a record or key: ' + field);
    if (spec.type === 'choices' && (!Array.isArray(value) || value.some(function (v) {{
      return !spec.choices.some(function (choice) {{ return choice.value === (v && typeof v === 'object' ? v.value : v); }});
    }}))) throw new Error('invalid multi-select choice: ' + field);
    if (spec.type === 'lookup') value = lookupValue(spec, value, false, 0);
    return 'pfx2gas:cell:v1:' + JSON.stringify({{type: spec.type, value: value}});
  }}
  if (spec.type === 'unsupported') throw new Error('unsupported Dataverse field type: ' + field);
  if (spec.type === 'choice' && !spec.choices.some(function (choice) {{ return choice.value === value; }}))
    throw new Error('invalid choice value: ' + field);
  if (spec.type === 'bool' && typeof value !== 'boolean') throw new Error('boolean field requires true or false: ' + field);
  if (spec.type === 'number' && (typeof value !== 'number' || !isFinite(value)))
    throw new Error('number field requires a finite number: ' + field);
  if (spec.type === 'date') {{
    var date = new Date(value);
    if (!isFinite(date.getTime())) throw new Error('invalid date: ' + field);
    return date.toISOString();
  }}
  if (typeof value === 'object') throw new Error('scalar field cannot store an object: ' + field);
  return value;
}}

function decodeCell(ds, field, value) {{
  var spec = DATA_CONTRACTS[ds].fields[field];
  if (!spec) throw new Error('unknown stored field in ' + ds + ': ' + field);
  if (value === '' || value === undefined || value === null) return DATA_CONTRACTS[ds].dataverse ? null : '';
  if (spec.type === 'lookup' || spec.type === 'choices') {{
    if (typeof value !== 'string' || value.indexOf('pfx2gas:cell:v1:') !== 0)
      throw new Error('invalid structured cell: ' + field);
    var envelope = JSON.parse(value.slice('pfx2gas:cell:v1:'.length));
    if (envelope.type !== spec.type) throw new Error('wrong structured cell type: ' + field);
    encodeCell(ds, field, envelope.value); // validate the full value before exposing it
    return spec.type === 'lookup' ? lookupValue(spec, envelope.value, true, 0) : envelope.value;
  }}
  return value instanceof Date ? value.toISOString() : value;
}}

function recordFromCells(ds, headers, row) {{
  var obj = {{}};
  headers.forEach(function (field, i) {{
    var value = decodeCell(ds, field, row[i]);
    obj[field] = value;
    DATA_CONTRACTS[ds].fields[field].aliases.forEach(function (alias) {{ obj[alias] = value; }});
  }});
  return obj;
}}

function listRows(ds) {{
  var sh = sheetFor(ds);
  var values = sh.getDataRange().getValues();
  if (values.length < 2) return [];
  var headers = values[0];
  return values.slice(1).map(function (row) {{ return recordFromCells(ds, headers, row); }});
}}

function createRow(ds, record) {{
  var sh = sheetFor(ds);
  var headers = sh.getRange(1, 1, 1, sh.getLastColumn()).getValues()[0];
  record = normalizeRecord(ds, record);
  var primary = DATA_CONTRACTS[ds].primaryKey;
  var cells = headers.map(function (h) {{
    var value = record[h] !== undefined ? record[h] : '';
    if (h === primary && (value === '' || value === null)) value = Utilities.getUuid();
    return encodeCell(ds, h, value);
  }});
  var idIdx = headers.indexOf(primary);
  if (idIdx >= 0 && sh.getDataRange().getValues().slice(1).some(function (row) {{ return String(row[idIdx]) === String(cells[idIdx]); }}))
    throw new Error('duplicate primary key in ' + ds);
  sh.appendRow(cells);
  return recordFromCells(ds, headers, cells);
}}

function patchRow(ds, base, record) {{
  var sh = sheetFor(ds);
  var values = sh.getDataRange().getValues();
  var headers = values[0] || [];
  var primary = DATA_CONTRACTS[ds].primaryKey;
  var idIdx = headers.indexOf(primary);
  var identity = recordIdentity(ds, base);
  var targetRow = -1;
  if (base && idIdx >= 0 && identity !== null) {{
    for (var r = 1; r < values.length; r++) {{
      if (String(values[r][idIdx]) === String(identity)) {{ targetRow = r + 1; break; }}
    }}
  }}
  if (targetRow < 0) {{
    if (base) throw new Error('patch base record was not found in ' + ds);
    return createRow(ds, record);
  }}
  record = normalizeRecord(ds, record);
  if (record[primary] !== undefined && String(record[primary]) !== String(identity))
    throw new Error('patch cannot change the primary key in ' + ds);
  // Validate every changed value before writing any cell. An invalid choice
  // must not leave the title updated while the rest of the save fails.
  var cells = headers.map(function (h, c) {{
    var value = record[h] !== undefined ? record[h] : values[targetRow - 1][c];
    return record[h] !== undefined ? encodeCell(ds, h, value) : value;
  }});
  sh.getRange(targetRow, 1, 1, headers.length).setValues([cells]);
  return recordFromCells(ds, headers, cells);
}}

function patchSingleRecord(ds, record) {{
  var contract = DATA_CONTRACTS[ds];
  if (!contract.sourcePrimaryKey) throw new Error('two-argument Patch requires exported source primary-key metadata: ' + ds);
  record = normalizeRecord(ds, record);
  var identity = recordIdentity(ds, record);
  if (identity === null) throw new Error('two-argument Patch requires an explicit source primary key: ' + ds);
  var values = sheetFor(ds).getDataRange().getValues();
  var column = (values[0] || []).indexOf(contract.primaryKey);
  if (column < 0) throw new Error('source primary-key column is missing: ' + ds);
  var matches = values.slice(1).filter(function (row) {{ return String(row[column]) === String(identity); }});
  if (matches.length > 1) throw new Error('ambiguous source primary key in ' + ds);
  // Never turn a validation or service error into a create. Only an absent
  // key takes the append path, while the caller holds the script write lock.
  return matches.length ? patchRow(ds, record, record) : createRow(ds, record);
}}

function removeRow(ds, record) {{
  var sh = sheetFor(ds);
  var values = sh.getDataRange().getValues();
  var headers = values[0] || [];
  var idIdx = headers.indexOf(DATA_CONTRACTS[ds].primaryKey);
  var identity = recordIdentity(ds, record);
  if (idIdx < 0 || identity === null) throw new Error('remove requires a primary key');
  assertNoRelationshipLinks_(ds, [String(identity)]);
  for (var r = 1; r < values.length; r++) {{
    if (String(values[r][idIdx]) === String(identity)) {{
      sh.deleteRow(r + 1);
      return {{ ok: true }};
    }}
  }}
  return {{ ok: false }};
}}

function removeRowsByIds(ds, ids) {{
  if (!Array.isArray(ids) || !ids.length) {{
    throw new Error('removeIf requires one or more explicit ids');
  }}
  var sh = sheetFor(ds);
  var values = sh.getDataRange().getValues();
  var headers = values[0] || [];
  var idIdx = headers.indexOf(DATA_CONTRACTS[ds].primaryKey);
  if (idIdx < 0) throw new Error('removeIf requires a primary key');
  var wanted = ids.map(String);
  assertNoRelationshipLinks_(ds, wanted);
  for (var r = values.length - 1; r >= 1; r--) {{
    if (wanted.indexOf(String(values[r][idIdx])) >= 0) sh.deleteRow(r + 1);
  }}
  return {{ ok: true }};
}}
"""

DATA_INIT_GS = """/**
 * DataInit.gs — one-time setup: creates the data workbook and tabs.
 * Run setup() once from the Apps Script editor after deploying.
 */
function setup() {{
  var props = PropertiesService.getScriptProperties();
  if (props.getProperty('DATA_SPREADSHEET_ID')) {{
    withDataWriteLock_(function () {{ setupRelationships_(ss()); setupPlanner_(ss()); setupDirectory_(ss()); }});
    return 'already initialized';
  }}
  var workbook = SpreadsheetApp.create({app_name!r} + ' — data');
  var specs = {tabs_json};
  specs.forEach(function (spec) {{
    var sh = workbook.getSheetByName(spec.name) || workbook.insertSheet(spec.name);
    sh.clear();
    var headers = spec.fields.map(function (f) {{ return f[0]; }});
    sh.getRange(1, 1, 1, headers.length).setValues([headers]);
    if (spec.rows && spec.rows.length) {{
      var body = spec.rows.map(function (row) {{
        row = normalizeRecord(spec.name, row);
        return headers.map(function (h, i) {{
          var value = row[h] === undefined ? '' : row[h];
          if (h === DATA_CONTRACTS[spec.name].primaryKey && (value === '' || value === null)) value = Utilities.getUuid();
          return encodeCell(spec.name, h, value);
        }});
      }});
      sh.getRange(2, 1, body.length, headers.length).setValues(body);
    }}
    sh.setFrozenRows(1);
  }});
  var choiceFields = {choices_json};
  var choiceNote = '';
  if (choiceFields.length) {{
    var ch = workbook.insertSheet('__Choices');
    ch.getRange(1, 1, 1, choiceFields.length).setValues([choiceFields]);
    ch.setFrozenRows(1);
    choiceNote = ' Populate the __Choices tab, then reload the app.';
  }}
  var defaultSheet = workbook.getSheetByName('Sheet1');
  setupRelationships_(workbook);
  setupPlanner_(workbook);
  setupDirectory_(workbook);
  if (defaultSheet && workbook.getSheets().length > 1) workbook.deleteSheet(defaultSheet);
  props.setProperty('DATA_SPREADSHEET_ID', workbook.getId());
  return 'created ' + workbook.getUrl() + choiceNote;
}}
"""

MANIFEST = """{{
  "timeZone": "America/New_York",
  "dependencies": {{}},
  "exceptionLogging": "STACKDRIVER",
  "runtimeVersion": "V8",
  "webapp": {{
    "executeAs": "{execute_as}",
    "access": "{access}"
  }},
  "oauthScopes": [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/userinfo.email"
  ]
}}
"""


def data_sources_with_fields(ir: AppIR) -> list:
    """External (non-collection) sources that should get a generated Sheet tab."""
    from ..data_contract import external_tables
    return external_tables(ir.data_sources)


def data_contracts(ir: AppIR) -> dict:
    from ..fx.naming import snake

    contracts = {}
    tables = data_sources_with_fields(ir)
    by_logical = {}
    for ds in tables:
        if ds.logical_name:
            by_logical.setdefault(ds.logical_name, []).append(ds.name)
    for ds in tables:
        primary = snake(ds.primary_key or "id")
        fields = {}
        for field in ds.fields:
            name = snake(field.name)
            if name in fields:
                raise ValueError(f"Duplicate stored field in {ds.name}: {name}")
            aliases = list(dict.fromkeys([*field.aliases, *(snake(alias) for alias in field.aliases), field.name]))
            if name == primary and primary != "id":
                aliases.append("id") # the runtime's generic row identity points at the source key
            fields[name] = {"type": field.type, "aliases": [alias for alias in aliases if alias != name],
                            "choices": field.choices}
            if field.type == 'lookup':
                fields[name].update(lookupSources=[name for target in field.lookup_targets for name in by_logical.get(target, [])],
                                    lookupTargetCount=len(field.lookup_targets))
        used = {}
        if ds.origin == "dataverse" and primary not in fields:
            raise ValueError(f"Missing Dataverse primary key in {ds.name}: {primary}")
        for name, spec in fields.items():
            for alias in [name, *spec["aliases"]]:
                if alias in used and used[alias] != name:
                    raise ValueError(f"Ambiguous field alias in {ds.name}: {alias}")
                used[alias] = name
        contracts[ds.name] = {"primaryKey": primary, "sourcePrimaryKey": bool(ds.primary_key),
                              "fields": fields, "dataverse": ds.origin == "dataverse"}
    return contracts


def render_code_gs(ir: AppIR) -> str:
    import json
    from ..relationships import relationship_contracts
    from .relationships import SERVER
    from .planner import SERVER as PLANNER_SERVER
    from .directory import SERVER as DIRECTORY_SERVER
    from ..services import service_contracts

    allowed = [ds.name for ds in data_sources_with_fields(ir)]
    if {'__pfx2gas_links', '__pfx2gas_planner', '__pfx2gas_directory'} & set(allowed):
        raise ValueError('source table collides with reserved relationship/connector storage')
    return CODE_GS.format(app_name=ir.name, data_sources_json=json.dumps(allowed),
                          contracts_json=json.dumps(data_contracts(ir)),
                          relationships_json=json.dumps(relationship_contracts(ir)),
                          services_json=json.dumps(service_contracts(ir))) + SERVER + PLANNER_SERVER + DIRECTORY_SERVER


def render_data_init(ir: AppIR) -> str:
    import json

    from ..fx.naming import snake as _snake

    tabs = []
    for ds in data_sources_with_fields(ir):
        headers = [_snake(f.name) for f in ds.fields]
        tabs.append({"name": ds.name, "fields": [[h, f.type]
                                                 for f, h in zip(ds.fields, headers)],
                     "rows": ds.sample_data[:100]})
    return DATA_INIT_GS.format(app_name=ir.name, tabs_json=json.dumps(tabs),
                               choices_json=json.dumps(ir.choice_fields))


def render_manifest(ir: AppIR) -> str:
    # MANIFEST is a format-template ({{ }} are literal braces); without
    # .format() it ships invalid JSON with doubled braces.
    import json
    from ..services import service_contracts
    manifest = json.loads(MANIFEST.format(access=ir.webapp_access, execute_as=ir.webapp_execute_as))
    if any(adapter['target']=='google-people-directory' for adapter in service_contracts(ir).values()):
        manifest['dependencies']['enabledAdvancedServices'] = [
            {'userSymbol':'People','serviceId':'peopleapi','version':'v1'}]
        manifest['oauthScopes'].append('https://www.googleapis.com/auth/directory.readonly')
    return json.dumps(manifest,indent=2)+'\n'
