"""Stage 4a: synthesize the server side (Code.gs, Data.gs, DataInit.gs, manifest)."""
from __future__ import annotations

from ..ir import AppIR

CODE_GS = """/**
 * Code.gs — web app entry point + API dispatcher.
 * Generated by pfx2gas from {app_name!r}; edit freely after generation.
 */
function doGet() {{
  return HtmlService.createTemplateFromFile('Index')
    .evaluate()
    .setTitle({app_name!r})
    .addMetaTag('viewport', 'width=device-width, initial-scale=1');
}}

/** Single API surface used by the generated client (gas-runtime.js serverRun). */
function api(ds, op, payload) {{
  payload = payload || {{}};
  switch (op) {{
    case 'list': return listRows(ds);
    case 'patch': return patchRow(ds, payload.base, payload.record);
    case 'create': return createRow(ds, payload.record);
    case 'remove': return removeRow(ds, payload.record);
    case 'removeIf': return removeRowsIf(ds, payload.predicate || {{}});
    default: throw new Error('unknown api op: ' + op);
  }}
}}

function ss() {{
  var props = PropertiesService.getScriptProperties();
  var id = props.getProperty('DATA_SPREADSHEET_ID');
  if (!id) throw new Error('Run DataInit.gs setup() once to create the data workbook.');
  return SpreadsheetApp.openById(id);
}}

function sheetFor(ds) {{
  var sh = ss().getSheetByName(ds);
  if (!sh) throw new Error('no sheet named ' + ds + '; run setup() again.');
  return sh;
}}

function listRows(ds) {{
  var sh = sheetFor(ds);
  var values = sh.getDataRange().getValues();
  if (values.length < 2) return [];
  var headers = values[0];
  return values.slice(1).map(function (row) {{
    var obj = {{}};
    headers.forEach(function (h, i) {{ obj[h] = row[i]; }});
    return obj;
  }});
}}

function createRow(ds, record) {{
  var sh = sheetFor(ds);
  var headers = sh.getRange(1, 1, 1, sh.getLastColumn()).getValues()[0];
  sh.appendRow(headers.map(function (h) {{ return record[h] !== undefined ? record[h] : ''; }}));
  return {{ ok: true }};
}}

function patchRow(ds, base, record) {{
  var sh = sheetFor(ds);
  var values = sh.getDataRange().getValues();
  var headers = values[0] || [];
  var idIdx = headers.indexOf('id');
  var targetRow = -1;
  if (base && idIdx >= 0 && base.id !== undefined && base.id !== null) {{
    for (var r = 1; r < values.length; r++) {{
      if (String(values[r][idIdx]) === String(base.id)) {{ targetRow = r + 1; break; }}
    }}
  }}
  if (targetRow < 0) return createRow(ds, record);
  headers.forEach(function (h, c) {{
    if (record[h] !== undefined) sh.getRange(targetRow, c + 1).setValue(record[h]);
  }});
  return {{ ok: true }};
}}

function removeRow(ds, record) {{
  var sh = sheetFor(ds);
  var values = sh.getDataRange().getValues();
  var headers = values[0] || [];
  var idIdx = headers.indexOf('id');
  if (idIdx < 0) throw new Error('remove requires an id column');
  for (var r = 1; r < values.length; r++) {{
    if (String(values[r][idIdx]) === String(record.id)) {{
      sh.deleteRow(r + 1);
      return {{ ok: true }};
    }}
  }}
  return {{ ok: false }};
}}

function removeRowsIf(ds, predicate) {{
  // Converted RemoveIf calls pass empty predicates; remove by field equality if given.
  var sh = sheetFor(ds);
  var values = sh.getDataRange().getValues();
  var headers = values[0] || [];
  var keys = Object.keys(predicate || {{}});
  for (var r = values.length - 1; r >= 1; r--) {{
    var match = keys.every(function (k) {{
      var c = headers.indexOf(k);
      return c >= 0 && String(values[r][c]) === String(predicate[k]);
    }});
    if (match) sh.deleteRow(r + 1);
  }}
  return {{ ok: true }};
}}
"""

DATA_INIT_GS = """/**
 * DataInit.gs — one-time setup: creates the data workbook and tabs.
 * Run setup() once from the Apps Script editor after deploying.
 */
function setup() {{
  var props = PropertiesService.getScriptProperties();
  if (props.getProperty('DATA_SPREADSHEET_ID')) return 'already initialized';
  var workbook = SpreadsheetApp.create({app_name!r} — data);
  var specs = {tabs_json};
  specs.forEach(function (spec) {{
    var sh = workbook.getSheetByName(spec.name) || workbook.insertSheet(spec.name);
    sh.clear();
    var headers = spec.fields.map(function (f) {{ return f[0]; }});
    sh.getRange(1, 1, 1, headers.length).setValues([headers]);
    sh.setFrozenRows(1);
  }});
  workbook.deleteSheet(workbook.getSheetByName('Sheet1'));
  props.setProperty('DATA_SPREADSHEET_ID', workbook.getId());
  return 'created ' + workbook.getUrl();
}}
"""

MANIFEST = """{{
  "timeZone": "America/New_York",
  "dependencies": {{}},
  "exceptionLogging": "STACKDRIVER",
  "runtimeVersion": "V8",
  "webapp": {{
    "executeAs": "USER_DEPLOYING",
    "access": "ANYONE_ANONYMOUS"
  }},
  "oauthScopes": [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/script.container.ui"
  ]
}}
"""


def data_sources_with_fields(ir: AppIR) -> list:
    return [ds for ds in ir.data_sources if ds.fields]


def render_code_gs(ir: AppIR) -> str:
    return CODE_GS.format(app_name=ir.name)


def render_data_init(ir: AppIR) -> str:
    import json
    tabs = [
        {"name": ds.name, "fields": [[f.name, f.type] for f in ds.fields]}
        for ds in data_sources_with_fields(ir)
    ]
    return DATA_INIT_GS.format(app_name=ir.name, tabs_json=json.dumps(tabs))


def render_manifest(ir: AppIR) -> str:
    return MANIFEST
